version: '3'
services: 
        zookeeper:
                image: shankershawn/kafka-zookeeper:latest
                pull_policy: always
                privileged: true
                restart: always
                networks:
                        - kafka-network
        kafka:
                image: shankershawn/kafka-server:latest
                pull_policy: always
                privileged: true
                restart: always
                networks:
                        - kafka-network
                environment:
                        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.198:9092
                depends_on:
                        - zookeeper
                ports:
                        - 9092:9092
networks:
        kafka-network:
