version: "2"
services:
        ojet_service:
                restart: always
                container_name: my_composed_ojet_app
                image: shankershawn/ojet:10.0.0
                ports:
                        - "8000:8000"
